### ISSUE TITLE
ACP only?

### ISSUE THREAD

**Issue by dmzx** [marttiphpbb/phpbb-ext-codemirror#1]
Can this be forum wide instead of ACP only?

**Comment by marttiphpbb** [comment]
What purpose could it serve?

**Comment by dmzx** [comment]
I want to use it in a controller outside ACP.
Did not check it if I can find it myself though just ask to be quicker :)

**Comment by marttiphpbb** [comment]
I will have a look into it.

**Comment by marttiphpbb** [comment]
https://www.phpbb.com/community/viewtopic.php?f=456&t=2473266&p=15020156#p15069826
